[SecureContext]
interface mixin NavigatorSms {
  readonly attribute SMSReceiver sms;
};

Navigator includes NavigatorSms;
WorkerNavigator includes NavigatorSms;

[
  SecureContext,
  Exposed=(Window,DedicatedWorker)]
interface SMS {
  readonly attribute DOMString content;
};

dictionary SMSReceiverOptions {
  unsigned long timeout;
};

[
  SecureContext,
  Exposed=(Window,DedicatedWorker)
] interface SMSReceiver {
  Promise<SMS> receive(optional SMSReceiverOptions options);
};
